// Type stub for the Compact-compiled contract module.
// The real file is generated by: compact compile src/bboard.compact ./src/managed/bboard
// This stub satisfies TypeScript's type checker in CI before the compiler runs.

export declare class Contract<T, W> {
  constructor(witnesses: W);
}

export declare const contractConfig: unknown;
export declare const witnesses: unknown;
