// Umbra Payroll Contract — TypeScript bindings entry point
// Auto-generated by: compact compile src/bboard.compact ./src/managed/bboard
// (The managed/ folder is produced by the Compact compiler at CI time)

import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";

export * from "./managed/bboard/contract/index.js";
export * from "./witnesses.js";

import { Contract } from "./managed/bboard/contract/index.js";
import { witnesses } from "./witnesses.js";

class ContractWrapper extends Contract<any, any> {
  constructor() {
    super(witnesses);
  }
}

// The compiled Umbra Payroll contract, ready for deployContract() / findDeployedContract()
export const CompiledUmbraPayrollContract = CompiledContract.make(
  "bboard",
  ContractWrapper as any
).pipe(
  CompiledContract.withCompiledFileAssets("./managed/bboard")
) as any;
