// Umbra Payroll Contract — TypeScript bindings entry point
// Auto-generated by: compact compile src/bboard.compact ./src/managed/bboard
// (The managed/ folder is produced by the Compact compiler at CI time)

import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";

export async function getCompiledUmbraPayrollContract() {
  const contractModule = await import("./managed/bboard/contract/index.js");
  const ContractClass = contractModule.Contract || (contractModule as any).default?.Contract;
  
  if (!ContractClass) {
    throw new Error("Failed to resolve Contract class from generated bindings");
  }

  const witnessesModule = await import("./witnesses.js");

  const DynamicContractWrapper = class extends ContractClass {
    constructor() {
      super(witnessesModule.witnesses as any);
    }
  };

  return CompiledContract.make(
    "bboard",
    DynamicContractWrapper as any
  ).pipe(
    CompiledContract.withCompiledFileAssets("/managed/bboard") // fetch from public/ at runtime
  ) as any;
}
